// automatically generated by the bpftime aot tool
// do not edit
#ifndef BPF_MAP_IDS_H
#define BPF_MAP_IDS_H

#include "common_map_helpers.h"

static const unsigned long long perf_SSL_events_id = ((unsigned long long)4 << 32);
static const unsigned long long ssl_data_id = ((unsigned long long)5 << 32);
static const unsigned long long start_ns_id = ((unsigned long long)6 << 32);
static const unsigned long long bufs_id = ((unsigned long long)7 << 32);

#endif // BPF_MAP_IDS_H
