// automatically generated by the bpftime aot tool
// do not edit
#ifndef __AOT_MAP_ID_H__
#define __AOT_MAP_ID_H__

// libbpf: map 'ctl_array': created successfully, fd=4
// libbpf: map 'vip_map': created successfully, fd=5
// libbpf: map 'fallback_cache': created successfully, fd=6
// libbpf: map 'lru_mapping': created successfully, fd=8
// libbpf: map 'ch_rings': created successfully, fd=7
// libbpf: map 'reals': created successfully, fd=9
// libbpf: map 'reals_stats': created successfully, fd=10
// libbpf: map 'lru_miss_stats': created successfully, fd=11
// libbpf: map 'vip_miss_stats': created successfully, fd=12
// libbpf: map 'stats': created successfully, fd=13
// libbpf: map 'quic_stats_map': created successfully, fd=14
// libbpf: map 'decap_vip_stats': created successfully, fd=15
// libbpf: map 'server_id_map': created successfully, fd=16
// libbpf: map 'tpr_stats_map': created successfully, fd=17
// libbpf: map 'server_id_stats': created successfully, fd=18

const unsigned long long ctl_array_id = (unsigned long long)4 << 32;
const unsigned long long vip_map_id = (unsigned long long)5 << 32;
const unsigned long long fallback_cache_id = (unsigned long long)6 << 32;
const unsigned long long lru_mapping_id = (unsigned long long)8 << 32;
const unsigned long long ch_rings_id = (unsigned long long)7 << 32;
const unsigned long long reals_id = (unsigned long long)9 << 32;
const unsigned long long reals_stats_id = (unsigned long long)10 << 32;
const unsigned long long lru_miss_stats_id = (unsigned long long)11 << 32;
const unsigned long long vip_miss_stats_id = (unsigned long long)12 << 32;
const unsigned long long stats_id = (unsigned long long)13 << 32;
const unsigned long long quic_stats_map_id = (unsigned long long)14 << 32;
const unsigned long long decap_vip_stats_id = (unsigned long long)15 << 32;
const unsigned long long server_id_map_id = (unsigned long long)16 << 32;
const unsigned long long tpr_stats_map_id = (unsigned long long)17 << 32;
const unsigned long long server_id_stats_id = (unsigned long long)18 << 32;

// const unsigned long long lru_map_id = 20 << 32;

#endif // __AOT_MAP_ID_H__

