// automatically generated by the bpftime aot tool
// do not edit
#ifndef BPF_MAP_IDS_H
#define BPF_MAP_IDS_H

static const unsigned long long config_map_id = ((unsigned long long)4 << 32);
static const unsigned long long targets_map_id = ((unsigned long long)5 << 32);

#endif // BPF_MAP_IDS_H
