// automatically generated by the bpftime aot tool
// do not edit
#ifndef BPF_MAP_IDS_H
#define BPF_MAP_IDS_H

#include "../common_map_helpers.h"


static const unsigned long long ctl_array_id = ((unsigned long long)4 << 32);
static const unsigned long long cntrs_array_id = ((unsigned long long)5 << 32);

#endif // BPF_MAP_IDS_H
