// automatically generated by the bpftime aot tool
// do not edit
#ifndef BPF_MAP_IDS_H
#define BPF_MAP_IDS_H

#include "../common_map_helpers.h"

static const unsigned long long icmpcnt_id = ((unsigned long long)4 << 32);
static unsigned long long __icmpcnt[1];

static __always_inline void* bpf_map_lookup_elem_aot(const unsigned long long* map, const void* key) {
  if (*map == icmpcnt_id)
    return &__icmpcnt[0];
  return _bpf_helper_ext_0001(*map, key);
}
static __always_inline int bpf_map_delete_elem_aot(const unsigned long long* map, const void* key) {
  return _bpf_helper_ext_0003(*map, key);
}
static __always_inline int bpf_map_update_elem_aot(const unsigned long long* map, void* key, void* value, unsigned long long flags) {
  return _bpf_helper_ext_0002(*map, key, value, flags);
}

#endif // BPF_MAP_IDS_H
